Oppgave endret hendelse
navikt/bidrag-arbeidsflyt pull request #93
Opened 2021-12-07 08:57 UTC by ugur93

2021-12-07 14:34 UTC, jactor-rises commented on src/main/kotlin/no/nav/bidrag/arbeidsflyt/dto/oppgaveHendelse.kt
> +    }
dette er en one-liner... hvorfor ikke:
```
fun harAktoerID() = ident != null && "AKTOERID".equals(ident.identType, ignoreCase = true) && ident.verdi != null
```

2021-12-07 14:35 UTC, jactor-rises commented on src/main/kotlin/no/nav/bidrag/arbeidsflyt/dto/oppgaveHendelse.kt
> +}
de ovenfor kan være "one-liners" også... og linjeskift bør avslutte ei fil...

2021-12-07 14:37 UTC, jactor-rises commented on src/main/kotlin/no/nav/bidrag/arbeidsflyt/hendelse/OppgaveHendelseListener.kt
> +}
eol

2021-12-07 14:40 UTC, jactor-rises commented on src/test/kotlin/no/nav/bidrag/arbeidsflyt/hendelse/OppgaveEndretHendelseListenerTest.kt
> +@ActiveProfiles(value = arrayOf(PROFILE_KAFKA_TEST, "test"))
hva er _"test"_?
hvorfor bare bruke konstant på _PROFILE_KAFKA_TEST_

2021-12-07 14:41 UTC, jactor-rises requested changes
bra... småting...

2021-12-07 14:47 UTC, jactor-rises commented on pom.xml
> +        <version>2.7.2</version>
jeg ser at d er jeg som har innført dette... dette er ikke en avhengighet i seg selv, men en overstyring av en sårbar avhengighet (fra **snyk**)... trenger vi denne?

2021-12-07 14:57 UTC, jactor-rises commented on pom.xml
> +        <version>2.7.2</version>
jeg har kjørt **snyk** på branchen din og ifølge plugin er dette riktig:
```
      <!-- snyk reported vulnerabilities -->
      <dependency>
        <groupId>org.apache.kafka</groupId>
        <artifactId>kafka-clients</artifactId>
        <version>2.7.2</version>
      </dependency>
      <dependency>
        <groupId>ch.qos.logback</groupId>
        <artifactId>logback-core</artifactId>
        <version>1.2.7</version>
      </dependency>
    </dependencies>
```

2021-12-07 14:58 UTC, jactor-rises commented on pom.xml
> +        <version>2.7.2</version>
**NB!** Det kan være forskjell på snyk plugin og rapport som genereres via GitHub

2021-12-08 08:41 UTC, ugur93 commented on pom.xml
> +        <version>2.7.2</version>
Fikset. Lurt tenkte ikke på det

2021-12-08 09:06 UTC, merged